export const GET_PLAYERS = 'GET_PLAYERS';
export const GET_PLAYERS_SUCCEEDED = 'GET_PLAYERS_SUCCEEDED';
export const GET_PLAYERS_FAILED = 'GET_PLAYERS_FAILED';

export const CHALLENGE = 'CHALLENGE';
export const CHALLENGE_SUCCEEDED = 'CHALLENGE_SUCCEEDED';
export const CHALLENGE_FAILED = 'CHALLENGE_FAILED';

export const UNCHALLENGE = 'UNCHALLENGE';
export const UNCHALLENGE_SUCCEEDED = 'UNCHALLENGE_SUCCEEDED';
export const UNCHALLENGE_FAILED = 'UNCHALLENGE_FAILED';

export const INCONSISTENT_STATE = 'INCONSISTENT_STATE';